language: generic

sudo: required

services:
  - docker

before_install:
  - docker build --tag yshrim12/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true yshrim12/react-test-app npm test

after_success:
  - docker build --tag yshrim12/docker-frontend ./frontend
  - docker build --tag yshrim12/docker-backend  ./backend
  - docker build --tag yshrim12/nginx  ./nginx

  - echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_ID}" --password-stdin

  - docker push yshrim12/docker-frontend
  - docker push yshrim12/docker-backend
  - docker push yshrim12/nginx

