version: "3"
services:
  frontend:
    depends_on:
      - "backend"
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - "./frontend:/app"
    stdin_open: true
    tty: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    container_name: nginx

  backend:
    depends_on:
      - "mysql"
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - "/app/node_modules"
      - "./backend:/app"
    env_file:
      - "env/backend.env"
    container_name: app_backend

  mysql:
    build: ./mysql
    #restart: unless-stopped
    container_name: app_mysql
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "./mysql/sqls/:/docker-entrypoint-initdb.d/"
    env_file:
      - "env/mysql.env"
    
networks:
  reacet-network:
    name: react-net
    external: true

volumes:
  mysql_data:
