version: "3"

services:
  frontend:
    image: yshrim12/docker-frontend # 도커허브에 저장된 이미지
    depends_on:
      - "backend"
    volumes:
      - "/app/node_modules"
      - "./frontend:/app"
    stdin_open: true
    tty: true
    mem_limit: 128m # 메모리 사이즈 명시
    container_name: frontend

  nginx:
    image: yshrim12/nginx # 도커허브에 저장된 이미지
    restart: always
    ports:
      - "80:80"
    mem_limit: 128m # 메모리 사이즈 명시    
    links: # 컨테이너간 연결
      - "frontend"
      - "backend"
    container_name: nginx

  backend:
    image: yshrim12/docker-backend # 도커허브에 저장된 이미지
    depends_on:
      - "mysql"
    volumes:
      - "/app/node_modules"
      - "./backend:/app"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
    mem_limit: 128m # 메모리 사이즈 명시
    container_name: backend

volumes:
  mysql_data:
